//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBulletin
    {
        public int fBu_ID { get; set; }
        public Nullable<System.DateTime> fBu_Date { get; set; }
        public int fBC_ID { get; set; }
        public string fBu_Title { get; set; }
        public string fBu_Content { get; set; }
    
        public virtual tBulletinClass tBulletinClass { get; set; }
    }
}
