//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDependentsTravel
    {
        public int fDT_ID { get; set; }
        public int fDe_ID { get; set; }
        public int fRD_ID { get; set; }
        public int fSt_ID { get; set; }
        public string fDT_Note { get; set; }
        public string fDT_Urgent { get; set; }
        public string fDT_UTel { get; set; }
        public string fDT_Insurance { get; set; }
        public Nullable<int> fSI_ID { get; set; }
        public Nullable<int> fTE_ID { get; set; }
        public Nullable<bool> fDT_Car { get; set; }
        public Nullable<bool> fDT_Hotel { get; set; }
        public string fDT_Relief { get; set; }
        public Nullable<decimal> fDT_RMoney { get; set; }
    
        public virtual tDependents tDependents { get; set; }
        public virtual tRegistrationDetail tRegistrationDetail { get; set; }
        public virtual tSpecialIdentity tSpecialIdentity { get; set; }
        public virtual tStatus tStatus { get; set; }
        public virtual tTraveEat tTraveEat { get; set; }
    }
}
