//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRestaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tRestaurant()
        {
            this.tMealClass = new HashSet<tMealClass>();
            this.tOpenTime = new HashSet<tOpenTime>();
            this.tRestaurantScores = new HashSet<tRestaurantScores>();
        }
    
        public int fRe_ID { get; set; }
        public string fRe_Name { get; set; }
        public string fRe_Content { get; set; }
        public string fRe_Tel { get; set; }
        public string fRe_Addr { get; set; }
        public Nullable<bool> fRe_Delivery { get; set; }
        public Nullable<decimal> fR_Price { get; set; }
        public int fEp_ID { get; set; }
        public int fMC_ID { get; set; }
        public string fRe_introduction { get; set; }
        public byte[] fRe_Image { get; set; }
        public string fRe_site { get; set; }
    
        public virtual tEmployee tEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMealClass> tMealClass { get; set; }
        public virtual tMessageCode tMessageCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tOpenTime> tOpenTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRestaurantScores> tRestaurantScores { get; set; }
    }
}
