//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW3.Areas.Albums.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelEntities1 : DbContext
    {
        public TravelEntities1()
            : base("name=TravelEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tAlbum> tAlbum { get; set; }
        public virtual DbSet<tForumMessage> tForumMessage { get; set; }
        public virtual DbSet<tMessageCode> tMessageCode { get; set; }
        public virtual DbSet<tPhoto> tPhoto { get; set; }
        public virtual DbSet<tTravelCase> tTravelCase { get; set; }
        public virtual DbSet<tEmployee> tEmployee { get; set; }
    }
}
