//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW3.Areas.Albums.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tForumMessage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tForumMessage()
        {
            this.tForumMessage1 = new HashSet<tForumMessage>();
        }
    
        public int fFM_ID { get; set; }
        public string fFM_Content { get; set; }
        public int fEp_ID { get; set; }
        public Nullable<System.DateTime> fFM_Date { get; set; }
        public Nullable<int> fFM_Dad { get; set; }
        public int fMC_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tForumMessage> tForumMessage1 { get; set; }
        public virtual tForumMessage tForumMessage2 { get; set; }
        public virtual tMessageCode tMessageCode { get; set; }
        public virtual tEmployee tEmployee { get; set; }
    }
}
