//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW3.Areas.EmployeeTrave.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelEntities2 : DbContext
    {
        public TravelEntities2()
            : base("name=TravelEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tDayTravel> tDayTravel { get; set; }
        public virtual DbSet<tRegistrationOpen> tRegistrationOpen { get; set; }
        public virtual DbSet<tTravelCase> tTravelCase { get; set; }
        public virtual DbSet<tCityCountry> tCityCountry { get; set; }
    }
}
