//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelEntities : DbContext
    {
        public TravelEntities()
            : base("name=TravelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tActivityList> tActivityList { get; set; }
        public virtual DbSet<tActivitySelect> tActivitySelect { get; set; }
        public virtual DbSet<tAlbum> tAlbum { get; set; }
        public virtual DbSet<tBulletin> tBulletin { get; set; }
        public virtual DbSet<tBulletinClass> tBulletinClass { get; set; }
        public virtual DbSet<tCityCountry> tCityCountry { get; set; }
        public virtual DbSet<tConnection> tConnection { get; set; }
        public virtual DbSet<tConnectionClass> tConnectionClass { get; set; }
        public virtual DbSet<tDayTravel> tDayTravel { get; set; }
        public virtual DbSet<tDependents> tDependents { get; set; }
        public virtual DbSet<tDependentsTravel> tDependentsTravel { get; set; }
        public virtual DbSet<tDetailScore> tDetailScore { get; set; }
        public virtual DbSet<tEmployee> tEmployee { get; set; }
        public virtual DbSet<tFamily> tFamily { get; set; }
        public virtual DbSet<tFieldValue> tFieldValue { get; set; }
        public virtual DbSet<tForumClass> tForumClass { get; set; }
        public virtual DbSet<tForumField> tForumField { get; set; }
        public virtual DbSet<tForumMessage> tForumMessage { get; set; }
        public virtual DbSet<tForumTitle> tForumTitle { get; set; }
        public virtual DbSet<tIdentity> tIdentity { get; set; }
        public virtual DbSet<tManergerHistory> tManergerHistory { get; set; }
        public virtual DbSet<tMealClass> tMealClass { get; set; }
        public virtual DbSet<tMealList> tMealList { get; set; }
        public virtual DbSet<tMessageCode> tMessageCode { get; set; }
        public virtual DbSet<tOpenTime> tOpenTime { get; set; }
        public virtual DbSet<tPenalty> tPenalty { get; set; }
        public virtual DbSet<tPhoto> tPhoto { get; set; }
        public virtual DbSet<tPushGood> tPushGood { get; set; }
        public virtual DbSet<tRegistrationDetail> tRegistrationDetail { get; set; }
        public virtual DbSet<tRegistrationOpen> tRegistrationOpen { get; set; }
        public virtual DbSet<tRelationship> tRelationship { get; set; }
        public virtual DbSet<tRestaurant> tRestaurant { get; set; }
        public virtual DbSet<tRestaurantScores> tRestaurantScores { get; set; }
        public virtual DbSet<tSampleProposal> tSampleProposal { get; set; }
        public virtual DbSet<tSector> tSector { get; set; }
        public virtual DbSet<tSpecialIdentity> tSpecialIdentity { get; set; }
        public virtual DbSet<tStatus> tStatus { get; set; }
        public virtual DbSet<tTraveEat> tTraveEat { get; set; }
        public virtual DbSet<tTravelCase> tTravelCase { get; set; }
        public virtual DbSet<tTravelClass> tTravelClass { get; set; }
        public virtual DbSet<tTravelDetail> tTravelDetail { get; set; }
        public virtual DbSet<tVoteDetail> tVoteDetail { get; set; }
        public virtual DbSet<tVoteItem> tVoteItem { get; set; }
        public virtual DbSet<tVoteOption> tVoteOption { get; set; }
        public virtual DbSet<tVoteProject> tVoteProject { get; set; }
    }
}
