//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tConnection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tConnection()
        {
            this.tConnection1 = new HashSet<tConnection>();
        }
    
        public int fCo_ID { get; set; }
        public int fEp_ID { get; set; }
        public System.DateTime fCo_Date { get; set; }
        public string fCo_Theme { get; set; }
        public int fCC_ID { get; set; }
        public string fCo_Content { get; set; }
        public byte[] fCo_Image { get; set; }
        public Nullable<System.DateTime> fCo_Clear { get; set; }
        public Nullable<int> fCo_Dad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tConnection> tConnection1 { get; set; }
        public virtual tConnection tConnection2 { get; set; }
        public virtual tConnectionClass tConnectionClass { get; set; }
        public virtual tEmployee tEmployee { get; set; }
    }
}
