//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetailScore
    {
        public int fDS_ID { get; set; }
        public Nullable<int> fEP_ID { get; set; }
        public Nullable<int> fTD_ID { get; set; }
        public string fDS_Score { get; set; }
    
        public virtual tEmployee tEmployee { get; set; }
        public virtual tTravelDetail tTravelDetail { get; set; }
    }
}
