//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tForumClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tForumClass()
        {
            this.tForumClass1 = new HashSet<tForumClass>();
            this.tForumField = new HashSet<tForumField>();
            this.tForumTitle = new HashSet<tForumTitle>();
        }
    
        public int fFC_ID { get; set; }
        public string fFC_Class { get; set; }
        public Nullable<int> fFC_Dad { get; set; }
        public byte[] fFC_Picture { get; set; }
        public string fFC_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tForumClass> tForumClass1 { get; set; }
        public virtual tForumClass tForumClass2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tForumField> tForumField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tForumTitle> tForumTitle { get; set; }
    }
}
