//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tManergerHistory
    {
        public int fMH_ID { get; set; }
        public System.DateTime fMH_Time { get; set; }
        public string fMH_Note { get; set; }
        public int fEp_ID { get; set; }
    
        public virtual tEmployee tEmployee { get; set; }
    }
}
