//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelEntities : DbContext
    {
        public TravelEntities()
            : base("name=TravelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tConnection> tConnection { get; set; }
        public virtual DbSet<tConnectionClass> tConnectionClass { get; set; }
        public virtual DbSet<tEmployee> tEmployee { get; set; }
        public virtual DbSet<tBulletin> tBulletin { get; set; }
        public virtual DbSet<tBulletinClass> tBulletinClass { get; set; }
    }
}
