//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRegistrationDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tRegistrationDetail()
        {
            this.tDependentsTravel = new HashSet<tDependentsTravel>();
            this.tFamily = new HashSet<tFamily>();
        }
    
        public int fRD_ID { get; set; }
        public int fTC_ID { get; set; }
        public int fEp_ID { get; set; }
        public Nullable<bool> fRD_Eat { get; set; }
        public decimal fRD_Grant { get; set; }
        public Nullable<System.DateTime> fRD_Date { get; set; }
        public int fSt_ID { get; set; }
        public string fRD_Urgent { get; set; }
        public string fRD_UTel { get; set; }
        public string fRD_Note { get; set; }
        public string fRD_Insurance { get; set; }
        public Nullable<System.DateTime> fRD_Fine { get; set; }
        public string fRD_Relief { get; set; }
        public Nullable<decimal> fRD_RMoney { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDependentsTravel> tDependentsTravel { get; set; }
        public virtual tEmployee tEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tFamily> tFamily { get; set; }
        public virtual tStatus tStatus { get; set; }
        public virtual tTravelCase tTravelCase { get; set; }
    }
}
