//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRestaurantScores
    {
        public int fRS_ID { get; set; }
        public int fEp_ID { get; set; }
        public int fRe_ID { get; set; }
        public Nullable<bool> fRS_Like { get; set; }
        public Nullable<int> fRS_Value { get; set; }
    
        public virtual tEmployee tEmployee { get; set; }
        public virtual tRestaurant tRestaurant { get; set; }
    }
}
