//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVoteProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tVoteProject()
        {
            this.tVoteDetail = new HashSet<tVoteDetail>();
            this.tVoteItem = new HashSet<tVoteItem>();
        }
    
        public int fVP_ID { get; set; }
        public string fVP_Name { get; set; }
        public string fVP_Description { get; set; }
        public byte[] fVP_Image { get; set; }
        public Nullable<System.DateTime> fVP_StartDate { get; set; }
        public Nullable<System.DateTime> fVP_EndDate { get; set; }
        public string fVP_Imagefile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tVoteDetail> tVoteDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tVoteItem> tVoteItem { get; set; }
    }
}
