//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVoteItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tVoteItem()
        {
            this.tVoteDetail = new HashSet<tVoteDetail>();
            this.tVoteOption = new HashSet<tVoteOption>();
        }
    
        public int fVI_ID { get; set; }
        public int fVP_ID { get; set; }
        public string fVI_Name { get; set; }
        public string fVI_Summary { get; set; }
        public string fVI_Type { get; set; }
        public byte[] fVI_Image { get; set; }
        public string fVI_Imagefile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tVoteDetail> tVoteDetail { get; set; }
        public virtual tVoteProject tVoteProject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tVoteOption> tVoteOption { get; set; }
    }
}
