//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_HW3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tVoteDetail
    {
        public int fVD_ID { get; set; }
        public int fVP_ID { get; set; }
        public int fVI_ID { get; set; }
        public int fVO_ID { get; set; }
        public int fEp_ID { get; set; }
    
        public virtual tEmployee tEmployee { get; set; }
        public virtual tVoteItem tVoteItem { get; set; }
        public virtual tVoteOption tVoteOption { get; set; }
        public virtual tVoteProject tVoteProject { get; set; }
    }
}
